---
- name: Install commons
  become: true
  block:
    - name: Install various packages
      ansible.builtin.package:
        name:
          - curl
          - wget
          - git
    - name: Install vim
      include_tasks:
        file: "tasks/vim.yml"
    - name: Install docker
      include_tasks:
        file: "tasks/docker.yml"

