---
- name: Display ansible_architecture
  hosts: server  # または対象のホスト (例: all, webservers)
  gather_facts: true # ファクト収集を有効にします (ansible_architecture を取得するため)



  tasks:
    - name: Show the value of ansible_architecture
      ansible.builtin.debug:
        var: ansible_architecture
    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture
    - name: show deb architecture
      ansible.builtin.debug:
        var: deb_architecture
