---
- name: Install docker
  block:
    - name: Install ca-certificates curl
      apt:
        update_cache: true
        pkg:
          - ca-certificates
          - curl
    - name: キーリングディレクトリの作成
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: add apt repository key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture

    - name: add apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename  }} stable"
        filename: docker
        state: present
        update_cache: yes

    - name: Install docker engine
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add user 'amemiya' to 'docker' group
      ansible.builtin.user:
        name: amemiya
        groups: docker
        append: yes  # 既存のグループに追加する場合に yes を指定します

