---
- name: Install and setup vim
  become: true
  block:
    - name: Install vim from apt
      package:
        name:
          - vim
    - name: Install vimrc
      template:
        src: templates/etc/vim/vimrc.j2
        dest: /etc/vim/vimrc
        mode: "0644"
        owner: root
        group: root
